name: (PR) Format Python Code

on:
  pull_request:
    branches: [ "main" ]  # PR이 main 브랜치에 머지될 때 실행

permissions:
  contents: write
  pull-requests: write  # PR에 직접 커밋할 수 있도록 권한 추가

jobs:
  python-code-format:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}  # PR의 소스 브랜치를 체크아웃

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          architecture: "x64"

      - name: Display Python version
        run: python --version

      - name: Install packages
        run: pip install black isort autopep8

      - name: Formatter
        run: |
          black .
          autopep8 --recursive --in-place --aggressive --aggressive .
          isort .

      - name: Commit format changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git diff --quiet || (git commit -am "Automated format fixes" && git push origin ${{ github.head_ref }})
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub Actions 제공 토큰 사용
